import logging
from typing import Optional, List, Dict, Any
from datetime import datetime
import github3
from ..config import settings
from ..models import ResourceShare, Message, PersonaState

logger = logging.getLogger(__name__)


class GitHubClient:
    """GitHub integration for resource tracking and experiment logs"""
    
    def __init__(self):
        self.github = None
        self.repo = None
        self._init_client()
    
    def _init_client(self):
        if settings.github_token:
            try:
                self.github = github3.login(token=settings.github_token)
                if settings.github_repo:
                    owner, repo_name = settings.github_repo.split("/")
                    self.repo = self.github.repository(owner, repo_name)
                logger.info("GitHub client initialized")
            except Exception as e:
                logger.warning(f"GitHub initialization failed: {e}")
        else:
            logger.info("No GitHub token provided, GitHub integration disabled")
    
    def create_resource_issue(
        self,
        resource: ResourceShare,
        experiment_name: str,
        persona_reactions: Dict[str, List[Message]]
    ) -> Optional[str]:
        """Create a GitHub issue for a shared resource with persona reactions"""
        if not self.repo:
            return None
        
        try:
            body = self._format_resource_issue_body(resource, experiment_name, persona_reactions)
            issue = self.repo.create_issue(
                title=f"[Resource] {resource.title}",
                body=body,
                labels=["resource", "experiment", "auto-generated"]
            )
            return issue.html_url
        except Exception as e:
            logger.error(f"Failed to create GitHub issue: {e}")
            return None
    
    def create_experiment_issue(
        self,
        experiment_name: str,
        config: Dict[str, Any],
        metrics: Dict[str, Any]
    ) -> Optional[str]:
        """Create a GitHub issue summarizing experiment results"""
        if not self.repo:
            return None
        
        try:
            body = self._format_experiment_issue_body(experiment_name, config, metrics)
            issue = self.repo.create_issue(
                title=f"[Experiment] {experiment_name}",
                body=body,
                labels=["experiment", "results", "auto-generated"]
            )
            return issue.html_url
        except Exception as e:
            logger.error(f"Failed to create experiment issue: {e}")
            return None
    
    def update_resource_issue(
        self,
        issue_url: str,
        new_reactions: Dict[str, List[Message]]
    ) -> bool:
        """Update an existing resource issue with new reactions"""
        if not self.repo:
            return False
        
        try:
            # Extract issue number from URL
            issue_number = int(issue_url.split("/")[-1])
            issue = self.repo.issue(issue_number)
            
            # Get current body and append new reactions
            current_body = issue.body or ""
            new_content = self._format_new_reactions(new_reactions)
            updated_body = current_body + "\n\n---\n\n### New Reactions\n" + new_content
            
            issue.edit(body=updated_body)
            return True
        except Exception as e:
            logger.error(f"Failed to update GitHub issue: {e}")
            return False
    
    def _format_resource_issue_body(
        self,
        resource: ResourceShare,
        experiment_name: str,
        persona_reactions: Dict[str, List[Message]]
    ) -> str:
        lines = [
            f"## Resource Shared in Experiment: {experiment_name}",
            "",
            f"**Title:** {resource.title}",
            f"**URL:** {resource.url}",
            f"**Description:** {resource.description}",
            f"**Shared by:** {resource.shared_by}",
            f"**Shared at:** {resource.shared_at.isoformat()}",
            f"**Tags:** {', '.join(resource.tags) if resource.tags else 'None'}",
            "",
            "## Persona Reactions",
            ""
        ]
        
        for persona_id, reactions in persona_reactions.items():
            for msg in reactions:
                lines.append(f"### {msg.sender_name} ({msg.timestamp.isoformat()})")
                lines.append(f"{msg.content}")
                lines.append("")
        
        lines.extend([
            "---",
            "*Auto-generated by Nexus AI Safety Research Platform*"
        ])
        
        return "\n".join(lines)
    
    def _format_experiment_issue_body(
        self,
        experiment_name: str,
        config: Dict[str, Any],
        metrics: Dict[str, Any]
    ) -> str:
        lines = [
            f"## Experiment Results: {experiment_name}",
            "",
            "### Configuration",
            f"- **Personas:** {config.get('persona_count', 'N/A')}",
            f"- **Topic:** {config.get('topic', 'N/A')}",
            f"- **Rounds:** {config.get('rounds', 'N/A')}",
            f"- **Duration:** {config.get('duration', 'N/A')}",
            "",
            "### Key Metrics",
        ]
        
        for key, value in metrics.items():
            lines.append(f"- **{key}:** {value}")
        
        lines.extend([
            "",
            "---",
            "*Auto-generated by Nexus AI Safety Research Platform*"
        ])
        
        return "\n".join(lines)
    
    def _format_new_reactions(self, reactions: Dict[str, List[Message]]) -> str:
        lines = []
        for persona_id, msgs in reactions.items():
            for msg in msgs:
                lines.append(f"**{msg.sender_name}** ({msg.timestamp.isoformat()}): {msg.content}")
        return "\n".join(lines) if lines else "No new reactions."
    
    def is_available(self) -> bool:
        return self.repo is not None


github_client = GitHubClient()